version: "3.8"

services: 
  server-python:
    container_name: server-python
    restart: always
    build: .
    ports: 
      - "192.168.0.6:4440:3000"
    volumes: 
      - .:/app
    links: 
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"
  